a=int(input("enter the integer number:"))
print("the value is:",a)
print("the type of a is:",type(a))
a=float(input("enter the decimal number:"))
print("the value is:",a)
print("the type of a is:",type(a))
a=(input("enter any string:"))
print("the string is:",a)
print("the type of a is:",type(a))
a=bool(input("enter true or false:"))
print("the value is:",a)
print("the type of a is:",type(a))
a=complex(input("enter the complex number:"))
print("the value is:",a)
print("the type of a is:",type(a))

