from tkinter import *
window=Tk()
def order():
    filewin=Toplevel(window)
    Label(filewin,text="Your account has been created",background='gray').pack()
window.geometry("500x500")
window.title("Registration form")
Label(text="Create a new Google account",font=10).pack(side=TOP)
Label(text="Enter your Details",font=8).pack(side=TOP)
First_name=Label(text="First Name:",font=8).place(x=50,y=70)
Last_name=Label(text="Last Name:",font=8).place(x=50,y=100)
username=Label(text="Username:",font=8).place(x=50,y=130)
password=Label(text="Password:",font=8).place(x=50,y=160)
Repassword=Label(text="Confirm Password:",font=8).place(x=50,y=190)
Phoneno=Label(text="Mobile Number:",font=8).place(x=50,y=220)
first_entry=Entry().place(x=200,y=72)
last_entry=Entry().place(x=200,y=102)
user_entry=Entry().place(x=200,y=132);side=Label(text="@gmail.com",font=8).place(x=320,y=128)
pass_entry=Entry(show='*').place(x=200,y=162)
repass_entry=Entry(show='*').place(x=200,y=192)
pno_entry=Entry().place(x=200,y=222)
chk=Checkbutton(text="I agree to the Google Terms of Services and Privacy",foreground='dim gray').place(x=150,y=260)
submit=Button(text="SUBMIT",font=6,command=order,activeforeground='blue').place(x=150,y=290)
quit=Button(text="Cancel",font=6,command=window.destroy,activeforeground='red').place(x=250,y=290)
window.mainloop()
